[tool.black]
line_length = 99
target_version = ["py310"]
exclude = ".git/"

[tool.isort]
py_version = "310"
profile = "black"
line_length = 99
extra_standard_library = ["typing_extensions"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
remove_imports = ["builtins"]
force_single_line = true
lines_after_imports = 2
skip_gitignore = true
atomic = true
honor_noqa = true
remove_redundant_aliases = true
src_paths = "src/aplaceforrover"
extend_skip_glob = ["*/migrations/*"]